version: 2
updates:

  # JS dependencies
  # it's different!
  - package-ecosystem: "npm"
    directory: "/different2"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
    reviewers:
      - "tobynorth"

  - package-ecosystem: "pip"
    directory: "/different2"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
    reviewers:
      - "tobynorth"
