version: 2
updates:

  # JS dependencies
  # it's different!
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "tobynorth"
    allow:
      - dependency-type: "all"
