#schedule: "every day"
requirements:
  - different/Pipfile:
      update: insecure
      pin: True
  - different/Pipfile.lock:
      update: insecure
      pin: True
# assignees:
#   - tobynorth
# branch_prefix: pyup/
